# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HW1_2UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(787, 453)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 40, 261, 361))
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(30, 50, 201, 271))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.btn3_1 = QtWidgets.QPushButton(self.splitter)
        self.btn3_1.setObjectName("btn3_1")
        self.btn3_2 = QtWidgets.QPushButton(self.splitter)
        self.btn3_2.setObjectName("btn3_2")
        self.btn3_3 = QtWidgets.QPushButton(self.splitter)
        self.btn3_3.setObjectName("btn3_3")
        self.btn3_4 = QtWidgets.QPushButton(self.splitter)
        self.btn3_4.setObjectName("btn3_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 40, 241, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn4_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4_4.setGeometry(QtCore.QRect(30, 258, 201, 64))
        self.btn4_4.setObjectName("btn4_4")
        self.btn4_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4_3.setGeometry(QtCore.QRect(30, 189, 201, 64))
        self.btn4_3.setObjectName("btn4_3")
        self.btn4_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4_1.setGeometry(QtCore.QRect(30, 51, 201, 64))
        self.btn4_1.setObjectName("btn4_1")
        self.btn4_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btn4_2.setGeometry(QtCore.QRect(30, 120, 201, 64))
        self.btn4_2.setObjectName("btn4_2")
        self.lm = QtWidgets.QPushButton(self.centralwidget)
        self.lm.setGeometry(QtCore.QRect(30, 160, 171, 61))
        self.lm.setObjectName("lm")
        self.label_lm = QtWidgets.QLabel(self.centralwidget)
        self.label_lm.setGeometry(QtCore.QRect(30, 240, 141, 41))
        self.label_lm.setObjectName("label_lm")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("mainWindow", "3. Edge Detection"))
        self.btn3_1.setText(_translate("mainWindow", " 3.1 Gaussian Blur"))
        self.btn3_2.setText(_translate("mainWindow", "3.2 Sobel X"))
        self.btn3_3.setText(_translate("mainWindow", "3.3 Sobel Y "))
        self.btn3_4.setText(_translate("mainWindow", "3.4 Magnitude"))
        self.groupBox_2.setTitle(_translate("mainWindow", "4. Transforms"))
        self.btn4_4.setText(_translate("mainWindow", "4.4 Shearing"))
        self.btn4_3.setText(_translate("mainWindow", "4.3 Rotation, Scaling"))
        self.btn4_1.setText(_translate("mainWindow", " 4.1 Resize"))
        self.btn4_2.setText(_translate("mainWindow", "4.2 Translation"))
        self.lm.setText(_translate("mainWindow", "Load Image"))
        self.label_lm.setText(_translate("mainWindow", "No image loaded"))
